Add terraform plan for Azure Container Instances
edekadigital/terraform-azure-modules pull request #17
Opened 2021-07-12 09:07 UTC by 5minpause

I created this plan for deploying an image as container instance. For sharing it here I variable-ized the hell out of it.
There are things like the ENV Vars that are not yet possible to set as variables, but I guess that will be done by the user of the script.

LMK what you think or if you need changes.
(Beware, I am on vacation soon until start of August…)

2021-11-27 08:20 UTC, selamanse commented
Hi @5minpause, first: thanks for your contribution and sorry for delayed review.

just a few requests before we can merge this:

2021-11-27 08:26 UTC, selamanse reviewed
please also take care about following 2 things:

- format files accordingly with `terraform fmt`
- configure a workflow for this module by using [an existing workflow definition](blob/main/.github/workflows/terraform-azure-sftp.yml) as a basis so it can pass a basic quality gate.

2021-11-27 08:26 UTC, selamanse commented on terraform-azure-container-instances/main.tf
> +provider "azurerm" {
please remove this provider assignment as we do not declare those directly in modules for reasons that are described best here: https://www.terraform.io/docs/language/modules/develop/providers.html#legacy-shared-modules-with-provider-configurations

2021-11-27 08:28 UTC, selamanse requested changes
see comments above

2022-02-14 13:22 UTC, closed without merging

2022-02-14 13:23 UTC, 5minpause commented
Thanks for your feedback. Sorry for my late reply. Since I left EDDI I will not be able to work on this project any longer.
Take care. Bye 👋