first draft of Azure devops agent module
edekadigital/terraform-azure-modules pull request #19
Opened 2021-11-16 09:17 UTC by nick-o

this module lets you build azure devops agent images for AWS and Azure Cloud using packer and then deploy them into AWS and/or Azure Cloud using terraform.

First Draft

2021-11-16 10:03 UTC, selamanse requested changes

2021-11-16 10:03 UTC, selamanse commented on terraform-azure-devops-agent/packer/scripts/install-base.sh
> +-----BEGIN PGP PUBLIC KEY BLOCK-----
try and get zulu key from here: http://repos.azulsystems.com/RPM-GPG-KEY-azulsystems

2021-11-16 10:03 UTC, selamanse commented on terraform-azure-devops-agent/azure_vm.tf
> +resource "azurerm_subnet" "bastion" {
do we need bastion for first draft?

2021-11-16 10:03 UTC, selamanse commented on terraform-azure-devops-agent/packer/bin/build-packer-aws-hcl.sh
> +#SG_IDS="$(aws ec2 describe-security-groups --filters Name=tag:Name,Values=webserver-reference,webserver_ref --query SecurityGroups[].GroupId --output text | tr '[:blank:]' ','),${SG_ID}"
remove commented code

2021-11-16 14:55 UTC, nick-o commented on terraform-azure-devops-agent/packer/bin/build-packer-azure-hcl.sh
> +    echo "${2} is empty!"
this is not needed in the azure image build script at all so I have removed it here. It is still required in the AWS AMI build script so will remain in there. The syntax is right here, the usage of this pre-existing function is: 
```
assert_non_zero "${VAR}" "VAR"
```
basically meaning the value and name of the var need to be passed in separately to get useful output.

2021-11-16 23:24 UTC, nick-o commented on terraform-azure-devops-agent/packer/devops-agent-aws.pkr.hcl
> +    "team" : "thundercats"
Done

2021-11-16 23:24 UTC, nick-o commented on terraform-azure-devops-agent/packer/devops-agent-aws.pkr.hcl
> +source "amazon-ebs" "ssm-example" {
done

2021-11-16 23:24 UTC, nick-o commented on terraform-azure-devops-agent/packer/devops-agent-aws.pkr.hcl
> +  # temporary_iam_instance_profile_policy_document {
removed comment

2021-11-16 23:25 UTC, nick-o commented on terraform-azure-devops-agent/packer/bin/build-packer-aws-hcl.sh
> +#SG_IDS="$(aws ec2 describe-security-groups --filters Name=tag:Name,Values=webserver-reference,webserver_ref --query SecurityGroups[].GroupId --output text | tr '[:blank:]' ','),${SG_ID}"
done

2021-11-16 23:36 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-base.sh
> +-----BEGIN PGP PUBLIC KEY BLOCK-----
that's done

2021-11-17 08:26 UTC, selamanse commented on terraform-azure-devops-agent/azure_image.tf
> +  resource_group_name = "crm-shared-rg"
use variable for rg

2021-11-17 08:29 UTC, selamanse commented on terraform-azure-devops-agent/packer/scripts/install-agent.sh
> +LINUX_AGENT_URL="https://vstsagentpackage.azureedge.net/agent/2.194.0/vsts-agent-linux-x64-2.194.0.tar.gz",
agent download should be separated to phase packer build

2021-11-17 09:55 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-agent.sh
> +LINUX_AGENT_URL="https://vstsagentpackage.azureedge.net/agent/2.194.0/vsts-agent-linux-x64-2.194.0.tar.gz",
agent version is now configurabe via `DEVOPS_AGENT_VERSION` env var, will use default of 2.194.0 if aforementioned env var is not set.

2021-11-17 22:31 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +NAME=best-devops-agent-ever-$INSTANCE_NAME
done

2021-11-17 22:42 UTC, nick-o commented on terraform-azure-devops-agent/azure_vm.tf
> +resource "azurerm_subnet" "bastion" {
really just the subnet for it and a NSG, not the actual bastion. But can get rid, just saved me some time

2021-11-18 08:19 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-agent.sh
> +DEVOPS_ORG_URL="https://dev.azure.com/EDDI-CRM",
done

2021-11-18 08:19 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-agent.sh
> +DEVOPS_AGENT_POOL="aws-by-thundercats",
done

2021-11-18 08:19 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-agent.sh
> +DEVOPS_ORG_TOKEN="TOKEEEEN"
token is pulled from Secretsmanager/KeyVault

2021-11-18 08:20 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/azure-vars.pkrtpl.hcl
> +az keyvault secret download --vault-name ${VAULT_NAME} --name ${SECRET_NAME} --file secret.txt
done

2021-11-18 08:20 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +LINUX_AGENT_URL="https://vstsagentpackage.azureedge.net/agent/2.194.0/vsts-agent-linux-x64-2.194.0.tar.gz"
done

2021-11-24 12:37 UTC, nick-o commented on terraform-azure-devops-agent/versions.tf
> +  region = "eu-central-1"
provider block has been removed as this is a module

2021-11-24 12:38 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-base.sh
> +-----BEGIN PGP PUBLIC KEY BLOCK-----
done

2021-11-24 12:38 UTC, nick-o commented on terraform-azure-devops-agent/azure_vm.tf
> +resource "azurerm_subnet" "bastion" {
removed

2021-11-24 12:38 UTC, nick-o commented on terraform-azure-devops-agent/azure_image.tf
> +  resource_group_name = "crm-shared-rg"
done

2021-11-24 12:39 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +DEVOPS_ORG_URL="https://dev.azure.com/EDDI-CRM"
done

2021-11-24 12:39 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +DEVOPS_AGENT_POOL="aws-by-thundercats"
done

2021-11-25 07:19 UTC, selamanse requested changes
Only a couple of minors left ;)

2021-11-25 07:19 UTC, selamanse commented on .github/workflows/terraform-azure-devops-agent-packer.yml
> +    #needs: [validate]
Uncomment to build only after verify

2021-11-25 07:19 UTC, selamanse commented on .github/workflows/terraform-azure-devops-agent-packer.yml
> +    #if: success() && github.ref == 'refs/heads/master'
Uncomment to build on master

2021-11-25 07:19 UTC, selamanse commented on terraform-azure-devops-agent/packer/scripts/install-base.sh
> +# -----BEGIN PGP PUBLIC KEY BLOCK-----
Why not remove this comment? Is it still necessary ?

2021-11-25 07:19 UTC, selamanse commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +#DEVOPS_ORG_URL= #"https://dev.azure.com/EDDI-CRM"
Remove pls

2021-11-25 07:19 UTC, selamanse commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +#DEVOPS_AGENT_POOL="aws-by-thundercats"
Remove pls

2021-11-25 07:38 UTC, nick-o commented on .github/workflows/terraform-azure-devops-agent-packer.yml
> +    #needs: [validate]
done

2021-11-25 07:38 UTC, nick-o commented on terraform-azure-devops-agent/packer/scripts/install-base.sh
> +# -----BEGIN PGP PUBLIC KEY BLOCK-----
done

2021-11-25 07:38 UTC, nick-o commented on .github/workflows/terraform-azure-devops-agent-packer.yml
> +    #if: success() && github.ref == 'refs/heads/master'
done

2021-11-25 07:38 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +#DEVOPS_ORG_URL= #"https://dev.azure.com/EDDI-CRM"
done

2021-11-25 07:39 UTC, nick-o commented on terraform-azure-devops-agent/packer/templates/install-agent.pkrtpl.hcl
> +#DEVOPS_AGENT_POOL="aws-by-thundercats"
done

2021-11-25 08:41 UTC, selamanse approved these changes

2021-11-25 08:41 UTC, merged